Style of the sidebar for icon download
bwinton/icons pull request #1
Opened 2017-07-03 16:56 UTC by aminalhazwani

I styled the sidebar following the design of the preferences sidebar of activity stream. I manually copied some of the styles (having a checkbox or radio button component would have been really helpful 😅). The CSS needs some cleaning/refactoring but I think we can do it before merging to production.

The naming of the options is temporary. In the meantime I placed 'Light' that corresponds to Grey 10 with 80% alpha channel and 'Dark' that corresponds to Grey 90 at 80%.

(I couldn't manage to run the website locally, if I run `npm run serve` I get a 404 page)

2017-07-04 14:47 UTC, bwinton requested changes
There are definitely some things we want to fix before we land it, but I think it's on it's way!

2017-07-04 14:47 UTC, bwinton commented on html/viewer/index.html
> +  <div id="icon-details" class="show">
We shouldn't show the details on pageload.  There's no content in it, it's kinda confusing, and it hides some icons.

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +  justify-content: flex-end;
The Cancel and Download buttons are too far over to the right.  This should probably be `center` or `space-around` (or maybe `space-between`)…

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +  background: url("../images/check.svg") no-repeat center center;
I don't think we should have the `check.svg` as a background for the `:not(:checked)` case…

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +  background-color: var(--blue-50);
Ditto here for the `background-color` of the `:not(:checked)` case…

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +  position: absolute;
On my iPhone 6s+ this hides the bottom of the details content.  Could we make this non-absolute, and add  `display:flex` to the `#icon-details` for layout instead?

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +  height: 100vh;
I'm a little concerned that this will look not-so-great when we load the SharedBanner…

2017-07-04 14:47 UTC, bwinton commented on html/viewer/index.html
> +      <div id="cancel">
The `cancel` button doesn't seem to do anything…  Did you need me to hook that up for you?

2017-07-04 14:47 UTC, bwinton commented on html/viewer/index.html
> -  <script src="https://firefoxux.github.io/SharedBanner/fxux-banner.min.js"></script>
ಠ_ಠ  Why no shared banner?

2017-07-04 14:47 UTC, bwinton commented on html/viewer/css/app.css
> +/** icon details checkbox **/
We should pull out the checkbox/radio button/slider css into its own file.

2017-07-04 15:03 UTC, aminalhazwani commented on html/viewer/index.html
> +  <div id="icon-details" class="show">
Oh yeah, sure, I forgot to remove the class 😅

2017-07-04 15:32 UTC, aminalhazwani commented on html/viewer/index.html
> +      <div id="cancel">
ahhh I now see the close button up there. if we have the close button this is not necessary, I removed the cancel 1938930

2017-07-04 15:42 UTC, nt1m commented on html/viewer/index.html
> -  <script src="https://firefoxux.github.io/SharedBanner/fxux-banner.min.js"></script>
It looks a bit odd tbh, and not photon enough.

2017-07-04 16:03 UTC, aminalhazwani commented on html/viewer/css/app.css
> +/** icon details checkbox **/
Yes! I originally pushed in `debug` mode. It should now be fixed with e2fa817

2017-07-04 16:03 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  background: url("../images/check.svg") no-repeat center center;
Yes! I originally pushed in `debug` mode. It should now be fixed with e2fa817

2017-07-04 16:37 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  background-color: var(--blue-50);
db04a04, I also added the `name` attribute to all radios and made `context-fill` the default one

2017-07-04 16:38 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  justify-content: flex-end;
I followed the spec of activity stream preferences sidebar

2017-07-04 19:02 UTC, nt1m commented on html/viewer/css/app.css
>    color: #f9f9fa;
This and above should probably use the variables as well.

2017-07-04 19:02 UTC, nt1m commented on html/viewer/index.html
> +          </div class="checkbox">
Here and below: closing tag should not include the class attribute

2017-07-05 09:25 UTC, aminalhazwani commented on html/viewer/index.html
> +          </div class="checkbox">
Good catch! 73f4103

2017-07-05 10:37 UTC, aminalhazwani commented on html/viewer/css/app.css
>    color: #f9f9fa;
c96e46e

2017-07-05 12:19 UTC, aminalhazwani commented on html/viewer/index.html
> -  <script src="https://firefoxux.github.io/SharedBanner/fxux-banner.min.js"></script>
Yeah, let's leave it for now and let's target it when we align the whole website style. See 09637ee

2017-07-05 12:19 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  height: 100vh;
Yeah, see 09637ee

2017-07-05 12:28 UTC, aminalhazwani commented on html/viewer/css/app.css
> +/** icon details checkbox **/
See c378495

2017-07-05 12:34 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  position: absolute;
The website is not really responsive. When we implement the new styles we could also make it work beautifully no matter the screen size. I anyway changed the layout to use flex 89e46dc

2017-07-05 12:53 UTC, aminalhazwani commented
@bwinton I should have addressed all requested changes! If you agree I would keep the responsive work and the photon style alignment in a separate PR. If we can bind the radio buttons to the fill attribute of the SVGs I then think we can merge with production. These are the requirements:

- if 'Contenxt Fill' is selected the SVG should have `fill="context-fill"`
- if 'Dark' is selected the SVG should have `fill="#0c0c0d" fill-opacity="0.8"`
- if 'Light' is selected the SVG shoud have `fill="#f9f9fa" fill-opacity="0.8"`

I will open a couple of issues for feature requests and to dos!

2017-07-05 13:59 UTC, bwinton approved these changes

2017-07-05 14:00 UTC, merged