Working download button
bwinton/icons pull request #2
Opened 2017-07-05 18:17 UTC by nt1m

2017-07-05 19:12 UTC, bwinton requested changes
Okay, I think that's enough complaining for the first round.  😉  Let's fix the stuff I mentioned, and I'll give it another pass.  Thanks!

2017-07-05 19:12 UTC, bwinton commented on html/viewer/index.html
> +            <input type="checkbox" value="svg" id="desktop-web" checked><label for="desktop-web"><span>Desktop/Web</span></label><br>
Do we need this value, and if so, should we add one to iOS and Android below?

2017-07-05 19:12 UTC, bwinton commented on html/viewer/css/app.css
> +#icon-details .preview .changeme {
Do we need the `.changeme` here?  I kinda think we don't…

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
> +  download.href = url;
I think we could do this without adding an ugly blob: url to the button…

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/icon-styles.js
> +      let blob = new Blob([svg.replace(/context-fill/g, fill)], {
Hmm.  If `fill` isn't passed in, this will return a kinda bad SVG.  What about using a default parameter here, or something other than object destructuring?

2017-07-05 19:12 UTC, bwinton commented on html/viewer/css/app.css
> +#icon-details .preview .changeme {
Also, what do you think about setting the fill when we set the color in the selectors below?

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
> +  requestMap: new Map(),
This feels a little like overengineering.  Why do we need a map?

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
>        fill.classList.add('changeme');
Since we're removing the fill, I don't think we need to add the `changeme` class, since the fill CSS property will only be picked up by things without a fill attribute of their own.

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
> +    };
So, the only thing we use from any calls to this method seem to be path and fileName (which I believe can be computed from path).  Maybe we could rename this `getSelectedPath` and just return that…

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
> +    element.classList.add("selected");
Let's make this one line: `selected.forEach(e => e.classList.toggle("selected", e === element));`

2017-07-05 19:12 UTC, bwinton commented on html/viewer/js/app.js
> +    iconContainer.addEventListener("click", function() {
Yeah, so, I don't want a million event listeners hanging around when we can have one on the parent element (which is why I implemented it that way in the code you removed above).  Let's go back to doing it like that.

2017-07-05 19:19 UTC, nt1m commented on html/viewer/js/app.js
> +  download.href = url;
What's wrong with a blob URL ?
I can do a data URL instead?

2017-07-05 19:23 UTC, nt1m commented on html/viewer/js/app.js
> +  requestMap: new Map(),
It's just to store the icons that already have been requested

2017-07-05 19:23 UTC, bwinton commented on html/viewer/js/app.js
> +  download.href = url;
I dunno, it just looked kinda ugly.  Although I did some more research, and it looks like that's the best we can do, so feel free to ignore this point.  ¯\_(ツ)_/¯

2017-07-05 19:24 UTC, bwinton commented on html/viewer/js/app.js
> +  requestMap: new Map(),
Let's get rid of it then.  YAGNI, as the saying goes…

2017-07-05 19:24 UTC, nt1m commented on html/viewer/js/app.js
> +    element.classList.add("selected");
:+1:

2017-07-05 19:25 UTC, nt1m commented on html/viewer/js/app.js
> +    iconContainer.addEventListener("click", function() {
What's wrong with lots of event listeners ? I think it's much cleaner than having tons of checking + a while loop just to check the right element.

2017-07-05 20:12 UTC, nt1m commented on html/viewer/index.html
> +            <input type="checkbox" value="svg" id="desktop-web" checked><label for="desktop-web"><span>Desktop/Web</span></label><br>
I could use the id instead of the value, but the value is more standard for this kind of stuff. (if this were inside a real form, it would submit ?svg=true)

2017-07-05 20:15 UTC, nt1m commented on html/viewer/js/app.js
> +    };
I tried this, but getting the filename from the full path (instead of the relative path) is actually quite ugly. My new commit has a different solution, lmk what you think.

2017-07-05 20:22 UTC, bwinton requested changes
Getting closer, but there's a few more things I think need fixing…

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> +    return icon;
Can we simplify this down to `return document.querySelector(".icon-display.selected");`?

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> +    element.classList.add("selected");
This should be unnecessary, since the toggle will add this class in the line above…

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> +    element.classList.add("selected");
Oh, also, when we want to clear the selection (by clicking on an empty area) we pass in nothing (or `undefined`), so this call will fail.

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> +        return;
It looks like we've lost the ability to click in empty space to deselect all the icons.  Is that true or is that handled somewhere else in the code?

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
>      document.querySelector('#icon-details .fill').addEventListener('click', e => {
If we're not using `e` anymore, we could simplify this to `…addEventListener('click', updatePreview);`.

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> -  selected.forEach(e => e.classList.remove('selected'));
Will this leave the icon selected when I hit the close button in the sidebar?  If so, how do I re-open the sidebar for that icon?

2017-07-05 20:22 UTC, bwinton commented on html/viewer/js/app.js
> +      fill.removeAttribute('fill');
If we remove the fill here (instead of changing its value), then when we download it, won't the `svg.replace(/context-fill/g, fill)` fail to change anything?

2017-07-05 20:34 UTC, nt1m commented on html/viewer/js/app.js
> +    element.classList.add("selected");
Good catch, thanks!

2017-07-05 20:35 UTC, nt1m commented on html/viewer/js/app.js
>      document.querySelector('#icon-details .fill').addEventListener('click', e => {
:+1:

2017-07-05 20:35 UTC, nt1m commented on html/viewer/js/app.js
> +    return icon;
:+1:

2017-07-06 11:07 UTC, nt1m commented
@bwinton I think I've addressed everything. Can you look at it again please? Thanks!

2017-07-07 14:09 UTC, bwinton commented on html/viewer/js/app.js
> +    document.querySelector('#icon-details .close-button').addEventListener('click', updateSidebar);
Oh!  This won't quite work, because it will pass in an event as the first argument instead of `undefined`, so the updateSidebar code will do the wrong thing…  I guess we need it to be:
```.addEventListener('click', () => updateSidebar());```
Sorry about that!

2017-07-07 14:15 UTC, bwinton commented on html/viewer/js/app.js
>    details.classList.toggle('show', icon);
This needs to be `details.classList.toggle('show', !!icon);`, otherwise it gets passed through as `undefined` instead of `false`, which will show the details if we click on an empty space.

2017-07-07 14:27 UTC, bwinton approved these changes

2017-07-07 14:28 UTC, bwinton commented
Merged manually!

2017-07-07 14:28 UTC, closed without merging