Minor style changes
bwinton/icons pull request #4
Opened 2017-07-10 14:02 UTC by aminalhazwani

Changes:

- sidebar preview like cards on activity stream
- 'context fill' fill option looks like code
- general layout and icons display, fully responsive now

I added an `overflow-y: auto;` to the sidebar. How does that look on win @bwinton?

Let me know folks what y'all think!

2017-07-10 14:39 UTC, bwinton requested changes

2017-07-10 14:39 UTC, bwinton commented on html/viewer/css/app.css
> +  width: 32px;
Yeah, no.  The icons are shown in the UI at 16px, not at 32px, so this change prevents people from seeing what they will actually look like.  If you want a bigger version to inspect the details, use the sidebar preview.

2017-07-10 14:39 UTC, bwinton commented on html/viewer/css/app.css
> +  margin: 20px;
This makes the sidebar overlap a bunch of the icons, which prevent us from selecting them.  We also can't click the empty space to the left of the icons to dismiss the sidebar anymore.  😞

2017-07-10 14:39 UTC, bwinton commented on html/viewer/index.html
> +            <input type="radio" name="fill" value="context-fill" id="context-fill" checked><label for="context-fill"><code><img src="images/context-fill.svg" alt="Context Fill"></code></label>
This breaks the font on the context fill option, as seen in [this image](https://cl.ly/1a381S2v2Y3A).

2017-07-10 14:39 UTC, bwinton commented on html/viewer/css/app.css
> +  overflow: hidden;
I'm not a fan, particularly because a number of our icons have [names which are indistinguishable](https://cl.ly/0I2J002a1Z1N) when you cut them off.

2017-07-10 14:39 UTC, bwinton commented on html/viewer/css/app.css
> +  transform: scale(1.1);
I like the bounce…  🙂

2017-07-10 14:39 UTC, bwinton commented on html/viewer/css/app.css
> +  overflow-y: auto;
I get a scrollbar on the preview pane now for some reason.  We should really remove that.

2017-07-11 08:27 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  margin: 20px;
The white empty space on the right looked odd, and what about mobile? My assumption is that the sidebar is an utility that is open if users want to download an icon, this is why it overlaps, it's meant to be temporary. I would keep it as it is, and if it's going to be an issue we can rethink that. Maybe flow the icons when the sidebar opens, let's see.

2017-07-11 08:32 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  width: 32px;
I made the icons slightly bigger because I wanted to enable users to easily scan and recognize icons in this grid list. The list is not meant to display icons at their original size but it is meant to let users find the icons that they need. I would keep this as it is.

2017-07-11 08:34 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  overflow: hidden;
The only issue I see is with the 'Arrowhead' series. We could rename the 'Arrowhead' to simply 'Arrow' or we could increase the margins around so that there is more space for longer strings. I'll try and keep you posted!

2017-07-11 08:37 UTC, aminalhazwani commented on html/viewer/index.html
> +            <input type="radio" name="fill" value="context-fill" id="context-fill" checked><label for="context-fill"><code><img src="images/context-fill.svg" alt="Context Fill"></code></label>
Good catch! It should be now fixed 2284797

2017-07-11 08:51 UTC, aminalhazwani commented on html/viewer/css/app.css
> +  overflow-y: auto;
Oki, I'll look for other possible solutions!

2017-07-11 12:21 UTC, brassy- commented on html/viewer/css/app.css
> +  margin: 20px;
@aminalhazwani I second Amin suggestion. The sidebar opens after the user clicks on an icon. I will ship as it is.

2017-07-11 12:26 UTC, brassy- commented on html/viewer/css/app.css
> +  width: 32px;
We received some feedback on the current size of the icons during our interviews. We believe that showing the icons bigger will improve the download experience. The size of the icon downloaded is going to be the real dimension(s).

2017-07-11 13:28 UTC, merged